# Generated by Django 6.0.2 on 2026-04-12 09:39

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_single_price', models.DecimalField(decimal_places=2, default=149.0, max_digits=8)),
                ('live_multi_price', models.DecimalField(decimal_places=2, default=399.0, max_digits=8)),
                ('recorded_single_price', models.DecimalField(decimal_places=2, default=199.0, max_digits=8)),
                ('recorded_multi_price', models.DecimalField(decimal_places=2, default=499.0, max_digits=8)),
                ('combo_single_price', models.DecimalField(decimal_places=2, default=299.0, max_digits=8)),
                ('combo_multi_price', models.DecimalField(decimal_places=2, default=699.0, max_digits=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Pricing',
                'verbose_name_plural': 'Global Pricing',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=5)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='webinars/instructors/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebinarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveWebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webinar_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, help_text='Auto generated from title', max_length=300)),
                ('is_test', models.BooleanField(default=False, help_text='Mark this webinar as Test / Demo only')),
                ('start_datetime', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('LIVE', 'Live'), ('ENDED', 'Ended')], default='UPCOMING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_webinars.instructor')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webinars', to='live_webinars.webinarcategory')),
            ],
            options={
                'ordering': ['start_datetime'],
            },
        ),
        migrations.CreateModel(
            name='WebinarPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_single_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('live_multi_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recorded_single_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recorded_multi_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('combo_single_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('combo_multi_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('webinar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webinarpricing', to='live_webinars.livewebinar')),
            ],
        ),
    ]
