# Generated by Django 6.0.2 on 2026-04-12 09:39

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('live_webinars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedWebinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webinar_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('zoom_recording_link', models.URLField(blank=True, help_text='Private link (paid users only)', null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_webinars', to='live_webinars.webinarcategory')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_webinars.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='RecordedWebinarPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('single_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('multi_user_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('webinar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='recorded_webinars.recordedwebinar')),
            ],
        ),
    ]
