# Generated by Django 6.0.2 on 2026-06-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_webinars', '0001_initial'),
        ('recorded_webinars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordedwebinar',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recorded_webinars', to='live_webinars.instructor'),
        ),
    ]
