# Generated by Django 6.0.2 on 2026-04-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('live_webinars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoomMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zoom_meeting_id', models.CharField(max_length=50)),
                ('uuid', models.CharField(blank=True, max_length=255, null=True)),
                ('topic', models.CharField(max_length=500)),
                ('join_url', models.URLField(max_length=500)),
                ('start_url', models.URLField(blank=True, max_length=500, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('start_time', models.DateTimeField()),
                ('duration', models.PositiveIntegerField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webinar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='zoom_meeting', to='live_webinars.livewebinar')),
            ],
        ),
    ]
