# Generated by Django 6.0.2 on 2026-02-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='paypal_plan_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
