# Generated by Django 6.0.2 on 2026-04-12 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('variant', models.CharField(choices=[('LIVE_SINGLE', 'Live Single'), ('LIVE_MULTI', 'Live Multi'), ('REC_SINGLE', 'Recorded Single'), ('REC_MULTI', 'Recorded Multi'), ('COMBO_SINGLE', 'Combo Single'), ('COMBO_MULTI', 'Combo Multi')], max_length=20)),
                ('price_snapshot', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'session_key', 'content_type', 'object_id', 'variant')},
            },
        ),
    ]
