# Generated by Django 6.0.2 on 2026-03-18 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_gateway_order_id_paymentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='object_id',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='webinar_ref_id',
            field=models.CharField(default='TEMP', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='webinar_title',
            field=models.CharField(default='TEMP', max_length=255),
            preserve_default=False,
        ),
    ]
