# Generated by Django 6.0.2 on 2026-03-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_content_type_orderitem_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='instructor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
